import type { Metadata } from 'next';
import React from 'react';
import { ToastContainer } from 'react-toastify';

import AppProviders from '@/providers/app-provider';

import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

//-----------------------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Bento',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen block relative bg-cushion h-full w-full before:fixed before:inset-0">
        <ToastContainer theme='dark' autoClose={2000} />
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
